### ISSUE TITLE
Login and Authentication

### ISSUE THREAD

**Issue by sureshhustle** [elvisfernandes/ng2-dfservice#2]
Hi,
   I am new to angular 2, Will please provide me code for Authentication and authorization on login.
and to display google map marker details  if i need  to take data from api i can't get it as a array object.

**I need to store hole table values as array object and store in markerData**
```

  let markerData = this.mapstore.(NEED VALUE) ;  **// Here i got as a observable and i need as a [obj,obj,..]**  

  MapsLoader.load(function (google) {
      var maps = new google.maps.Map(el, {
        center: new google.maps.LatLng(20.5937, 78.9629),
        zoom: 10,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      });

      var infowindows = [];
      var contents = [];
      var markers = [];

    
      for (var i = 0; i < markerData.length; i++) {
        var pos = new google.maps.LatLng(markerData[i].latitude, markerData[i].longitude);
        var title = markerData[i].title;
       
        markers[i] = new google.maps.Marker({
          position: pos,
          map: maps,
          title: title,
          id: i
        });
      }

      return maps;
    });

```

**Comment by elvisfernandes** [comment]
Hi @sureshhustle ,

Please refer to the [dfservice-example](https://github.com/elvisfernandes/dfservice-example) repo to see the authentication method working.

Regarding the Google Maps issue: if your doubt is how to get data from DF using ng2-dfservice, please note that this is an **asynchronous** request. So it is impossible to have an object array for  `markerdata` immediately after executing

    let markerData = this.mapstore.(NEED VALUE) ;

. You'll have to wait until this request is completed, that's why you get an Observable in return. Try this:

    this.mapstore.(NEED VALUE).forEach( (your_data) => {
        // Use the return from DB here, which will be available in the your_data variable,
        // which may be an array of DFModel objects
    });

Remember that if you're using data binding from `this.mapstore` to wherever you're using this data you don't need to use the Observable callback I mentioned above. Take a look at an usage of this at [this binding at dfservice-example](https://github.com/elvisfernandes/dfservice-example/blob/master/src/app/app.component.html#L49).
